export { default as Broker } from '../Broker/broker';
export { default as CalculatorPageComponent } from '../Calculator/calculator';
export { default as Solutions } from '../Solutions/solutions';
export { default as Team } from '../Team/team';
export { default as Paper } from '../Atrticles/paper';
export { default as Analysis } from '../Analysis/analysis';
export { default as Reviews } from '../Reviews/reviews';
export { default as Services } from '../Services/services';
export { default as Enroll } from '../Enroll/enroll';
